# Copyright (C) 2016 and later: Unicode, Inc. and others.
# License & terms of use: http://www.unicode.org/copyright.html

from collections import namedtuple
import glob as pyglob
from distutils.sysconfig import parse_makefile

ExecutionRequest = namedtuple("ExecutionRequest", ["dep_files", "input_files", "output_files", "tool", "args"])


class Config(object):
    def has_feature(self, feature_name):
        # TODO
        return True

    def max_parallel(self):
        return True

    def coll_han_type(self):
        # Either "unihan" or "implicithan"
        return "unihan"


def glob(pattern):
    in_dir = "." # TODO
    result_paths = pyglob.glob("{IN_DIR}/{PATTERN}".format(
        IN_DIR =in_dir,
        PATTERN = pattern
    ))
    return [v[len(in_dir)+1:] for v in result_paths]


def get_command_lines(request, common_vars):
    if request.tool == "echo":
        assert len(request.dep_files) == 0
        assert len(request.input_files) == 0
        assert len(request.output_files) == 1
        output_file = request.output_files[0]
        cmds = ["rm -f {OUTPUT_FILE}".format(**common_vars, OUTPUT_FILE = output_file)]
        cmds += [
            "echo \"{LINE}\" >> {OUTPUT_FILE}".format(**common_vars,
                OUTPUT_FILE = output_file,
                LINE = line.replace("\"", "\\\"")
            )
            for line in request.args.split("\n")]
        return cmds
    if request.tool == "mkinstalldirs":
        return ["sh ../mkinstalldirs {ARGS}".format(ARGS = request.args)]
    return ["../bin/{TOOL} {ARGS}".format(TOOL = request.tool, ARGS = request.args)]


def generate_index_file(locales, cldr_version, common_vars):
    formatted_locales = "\n".join(["        %s {\"\"}" % v for v in locales])
    # TODO: CLDRVersion is required only in the base file
    return ("// Warning this file is automatically generated\n"
            "{INDEX_NAME}:table(nofallback) {{\n"
            "    CLDRVersion {{ \"{CLDR_VERSION}\" }}\n"
            "    InstalledLocales {{\n"
            "{FORMATTED_LOCALES}\n"
            "    }}\n"
            "}}").format(**common_vars, CLDR_VERSION = cldr_version, FORMATTED_LOCALES = formatted_locales)


def main():
    requests = []

    common = {
        "IN_DIR": ".",
        "OUT_DIR": "outdir",
        "TMP_DIR": "outdir/tmp",
        "INDEX_NAME": "res_index",
        "ICUDATA_CHAR": "l",  # TODO: Pull from configure script
        "GENRB_CLDR_VERSION": "33.1",  # TODO
    }

    config = Config()

    # DIRECTORIES
    build_dirs = [v.format(**common) for v in ["{OUT_DIR}", "{OUT_DIR}/curr", "{OUT_DIR}/lang", "{OUT_DIR}/region", "{OUT_DIR}/zone", "{OUT_DIR}/unit", "{OUT_DIR}/brkitr", "{OUT_DIR}/coll", "{OUT_DIR}/rbnf", "{OUT_DIR}/translit", "{TMP_DIR}", "{TMP_DIR}/curr", "{TMP_DIR}/lang", "{TMP_DIR}/locales", "{TMP_DIR}/region", "{TMP_DIR}/zone", "{TMP_DIR}/unit", "{TMP_DIR}/coll", "{TMP_DIR}/rbnf", "{TMP_DIR}/translit", "{TMP_DIR}/brkitr"]]
    requests += [
        ExecutionRequest(
            dep_files = [],
            input_files = [],
            output_files = [],
            tool = "mkinstalldirs",
            args = " ".join(build_dirs)
        )
    ]

    # CONFUSABLES
    if config.has_feature("confusables"):
        txt1 = "unidata/confusables.txt"
        txt2 = "unidata/confusablesWholeScript.txt"
        cfu = "confusables.cfu"
        requests += [
            ExecutionRequest(
                dep_files = [],
                input_files = [txt1, txt2],
                output_files = [cfu],
                tool = "gencfu",
                args = "-c -i {OUT_DIR} -r {IN_DIR}/{TXT1} -w {IN_DIR}/{TXT2} -o {OUT_DIR}/{CFU}".format(**common,
                    TXT1 = txt1,
                    TXT2 = txt2,
                    CFU = cfu
                )
            )
        ]

    # UConv Name Aliases
    if config.has_feature("cnvalias"):
        input_file = "mappings/convrtrs.txt"
        output_file = "cnvalias.icu"
        requests += [
            ExecutionRequest(
                dep_files = [],
                input_files = [input_file],
                output_files = [output_file],
                tool = "gencnval",
                args = "-d {OUT_DIR} {IN_DIR}/{INPUT_FILE}".format(**common,
                    INPUT_FILE = input_file,
                    OUTPUT_FILE = output_file
                )
            )
        ]

    # UConv Conversion Table Files
    if config.has_feature("uconv"):
        input_files = glob("mappings/*.ucm")
        output_files = ["%s.cnv" % v[9:-4] for v in input_files]
        if config.max_parallel():
            # Do each cnv file on its own
            requests += [
                ExecutionRequest(
                    dep_files = [],
                    input_files = [input_file],
                    output_files = [output_file],
                    tool = "makeconv",
                    args = "-c -d {OUT_DIR} {IN_DIR}/{INPUT_FILE}".format(**common,
                        INPUT_FILE = input_file
                    )
                )
                for (input_file, output_file) in zip(input_files, output_files)
            ]
        else:
            # Do all cnv files in one command
            # Faster overall but cannot be parallelized
            requests += [
                ExecutionRequest(
                    dep_files = [],
                    input_files = input_files,
                    output_files = output_files,
                    tool = "makeconv",
                    args = "-c -d {OUT_DIR} {INPUT_FILES}".format(**common,
                        INPUT_FILES = " ".join(input_files)
                    )
                )
            ]

    # BRK Files
    if config.has_feature("break-iterator"):
        input_files = glob("brkitr/rules/*.txt")
        output_files = ["brkitr/%s.brk" % v[13:-4] for v in input_files]
        requests += [
            ExecutionRequest(
                dep_files = [],
                input_files = [input_file],
                output_files = [output_file],
                tool = "genbrk",
                args = "-c -i {IN_DIR} -r {IN_DIR}/{INPUT_FILE} -o {OUT_DIR}/{OUTPUT_FILE}".format(**common,
                    INPUT_FILE = input_file,
                    OUTPUT_FILE = output_file
                )
            )
            for (input_file, output_file) in zip(input_files, output_files)
        ]

    # SPP FILES
    if config.has_feature("string-prep"):
        input_files = glob("sprep/*.txt")
        output_files = ["%s.spp" % v[6:-4] for v in input_files]
        bundle_names = [v[6:-4] for v in input_files]
        requests += [
            ExecutionRequest(
                dep_files = [],
                input_files = [input_file],
                output_files = [output_file],
                tool = "gensprep",
                args = "-d {OUT_DIR} -i {OUT_DIR} -s {IN_DIR}/sprep -b {BUNDLE_NAME} -m {IN_DIR}/unidata -u 3.2.0 {BUNDLE_NAME}.txt".format(**common,
                    INPUT_FILE = input_file,
                    OUTPUT_FILE = output_file,
                    BUNDLE_NAME = bundle_name
                )
            )
            for (input_file, output_file, bundle_name) in zip(input_files, output_files, bundle_names)
        ]

    # Dict Files
    if config.has_feature("dictionaries"):
        input_files = glob("brkitr/dictionaries/*.txt")
        output_files = ["brkitr/%s.dict" % v[20:-4] for v in input_files]
        extra_options_map = {
            "brkitr/dictionaries/burmesedict.txt": "--bytes --transform offset-0x1000",
            "brkitr/dictionaries/cjdict.txt": "--uchars",
            "brkitr/dictionaries/khmerdict.txt": "--bytes --transform offset-0x1780",
            "brkitr/dictionaries/laodict.txt": "--bytes --transform offset-0x0e80",
            "brkitr/dictionaries/thaidict.txt": "--bytes --transform offset-0x0e00"
        }
        extra_optionses = [extra_options_map[v] for v in input_files]
        requests += [
            ExecutionRequest(
                dep_files = [],
                input_files = [input_file],
                output_files = [output_file],
                tool = "gendict",
                args = "{EXTRA_OPTIONS} -c -i {OUT_DIR} {INPUT_FILE} {OUT_DIR}/{OUTPUT_FILE}".format(**common,
                    INPUT_FILE = input_file,
                    OUTPUT_FILE = output_file,
                    EXTRA_OPTIONS = extra_options
                )
            )
            for (input_file, output_file, extra_options) in zip(input_files, output_files, extra_optionses)
        ]

    # NRM Files
    if config.has_feature("normalization"):
        input_files = glob("in/*.nrm")
        input_files.remove("in/nfc.nrm")  # nfc.nrm is pre-compiled into C++
        output_files = ["%s" % v[3:] for v in input_files]
        requests += [
            ExecutionRequest(
                dep_files = [],
                input_files = [input_file],
                output_files = [output_file],
                tool = "icupkg",
                args = "-t{ICUDATA_CHAR} {IN_DIR}/{INPUT_FILE} {OUT_DIR}/{OUTPUT_FILE}".format(**common,
                    INPUT_FILE = input_file,
                    OUTPUT_FILE = output_file
                )
            )
            for (input_file, output_file) in zip(input_files, output_files)
        ]

    # Collation Dependency File (ucadata.icu)
    if config.has_feature("coll"):
        input_file = "in/coll/ucadata-%s.icu" % config.coll_han_type()
        output_file = "coll/ucadata.icu"
        requests += [
            ExecutionRequest(
                dep_files = [],
                input_files = [input_file],
                output_files = [output_file],
                tool = "icupkg",
                args = "-t{ICUDATA_CHAR} {IN_DIR}/{INPUT_FILE} {OUT_DIR}/{OUTPUT_FILE}".format(**common,
                    INPUT_FILE = input_file,
                    OUTPUT_FILE = output_file
                )
            )
        ]

    # Unicode Character Names
    if config.has_feature("unames"):
        input_file = "in/unames.icu"
        output_file = "unames.icu"
        requests += [
            ExecutionRequest(
                dep_files = [],
                input_files = [input_file],
                output_files = [output_file],
                tool = "icupkg",
                args = "-t{ICUDATA_CHAR} {IN_DIR}/{INPUT_FILE} {OUT_DIR}/{OUTPUT_FILE}".format(**common,
                    INPUT_FILE = input_file,
                    OUTPUT_FILE = output_file
                )
            )
        ]

    # Misc Data Res Files
    if config.has_feature("misc"):
        # TODO: Treat each misc file separately
        input_files = glob("misc/*.txt")
        input_basenames = [v[5:] for v in input_files]
        output_files = ["%s.res" % v[:-4] for v in input_basenames]
        requests += [
            ExecutionRequest(
                dep_files = [],
                input_files = [input_file],
                output_files = [output_file],
                tool = "genrb",
                args = "-k -q -i {OUT_DIR} -s {IN_DIR}/misc -d {OUT_DIR} {INPUT_BASENAME}".format(**common,
                    INPUT_BASENAME = input_basename
                )
            )
            for (input_file, output_file, input_basename) in zip(input_files, output_files, input_basenames)
        ]

    # Specialized Locale Data Res Files
    specialized_sub_dirs = [
        # (input dirname, output dirname, resfiles.mk path, use pool file, dep files)
        ("locales",  None,       "resfiles.mk",  True,  []),
        ("curr",     "curr",     "resfiles.mk",  True,  []),
        ("lang",     "lang",     "resfiles.mk",  True,  []),
        ("region",   "region",   "resfiles.mk",  True,  []),
        ("zone",     "zone",     "resfiles.mk",  True,  []),
        ("unit",     "unit",     "resfiles.mk",  True,  []),
        ("coll",     "coll",     "colfiles.mk",  False, ["coll/ucadata.icu"]),
        ("brkitr",   "brkitr",   "brkfiles.mk",  False, []),
        ("rbnf",     "rbnf",     "rbnffiles.mk", False, []),
        ("translit", "translit", "trnsfiles.mk", False, [])
    ]

    for sub_dir, out_sub_dir, resfile_name, use_pool_bundle, dep_files in specialized_sub_dirs:
        out_prefix = "%s/" % out_sub_dir if out_sub_dir else ""
        extra_options = "--usePoolBundle" if use_pool_bundle else ""
        if config.has_feature(sub_dir):
            input_pool_file = "%s/pool.res" % sub_dir
            # TODO: Clean this up for translit
            if sub_dir == "translit":
                input_files = ["translit/root.txt", "translit/en.txt", "translit/el.txt"]
            else:
                input_files = glob("%s/*.txt" % sub_dir)
            input_basenames = [v[len(sub_dir)+1:] for v in input_files]
            output_files = ["%s%s" % (out_prefix, v[:-4]) for v in input_basenames]
            if config.max_parallel():
                # Do each res file on its own
                requests += [
                    ExecutionRequest(
                        dep_files = dep_files,
                        input_files = [input_file] + [input_pool_file],
                        output_files = [output_file],
                        tool = "genrb",
                        args = "{EXTRA_OPTIONS} -k -i {OUT_DIR} -s {IN_DIR}/{IN_SUB_DIR} -d {OUT_DIR}/{OUT_PREFIX} {INPUT_BASENAME}".format(**common,
                            EXTRA_OPTIONS = extra_options,
                            IN_SUB_DIR = sub_dir,
                            OUT_PREFIX = out_prefix,
                            INPUT_BASENAME = input_basename
                        )
                    )
                    for (input_file, output_file, input_basename) in zip(input_files, output_files, input_basenames)
                ]
            else:
                # Do all res files in one command
                # Faster overall but cannot be parallelized
                requests += [
                    ExecutionRequest(
                        dep_files = dep_files,
                        input_files = input_files + [input_pool_file],
                        output_files = output_files,
                        tool = "genrb",
                        args = "{EXTRA_OPTIONS} -k -i {OUT_DIR} -s {IN_DIR}/{IN_SUB_DIR} -d {OUT_DIR}/{OUT_PREFIX} {INPUT_BASENAMES}".format(**common,
                            EXTRA_OPTIONS = extra_options,
                            IN_SUB_DIR = sub_dir,
                            OUT_PREFIX = out_prefix,
                            INPUT_BASENAMES = " ".join(input_basenames)
                        )
                    )
                ]
            # Generate index txt file
            # TODO: Change .mk files to .py files so they can be loaded directly.
            # Reading these files as .py will be required for Bazel.
            mk_values = parse_makefile("{IN_DIR}/{IN_SUB_DIR}/{RESFILE_NAME}".format(**common, IN_SUB_DIR = sub_dir, RESFILE_NAME = resfile_name))
            cldr_version = "33.1"  # TODO: from .mk file
            locales = ["en", "my_MM"]  # TODO: from .mk file
            #locales = list(sorted(v[:-4] for v in mk_values["CURR_SOURCE"].split(" ")))
            index_file_txt = "{TMP_DIR}/{IN_SUB_DIR}/{INDEX_NAME}.txt".format(**common, IN_SUB_DIR = sub_dir)
            requests += [
                ExecutionRequest(
                    dep_files = [],
                    input_files = [],
                    output_files = [index_file_txt],
                    tool = "echo",
                    args = generate_index_file(locales, cldr_version, common)
                )
            ]
            # Generate index res file
            index_res_file = "{OUT_DIR}/{OUT_PREFIX}{INDEX_NAME}.res".format(**common, OUT_PREFIX = out_prefix)
            requests += [
                ExecutionRequest(
                    dep_files = [index_file_txt],
                    input_files = [],
                    output_files = [index_res_file],
                    tool = "genrb",
                    args = "-k -i {OUT_DIR} -s {TMP_DIR}/{IN_SUB_DIR} -d {OUT_DIR}/{OUT_PREFIX} {INDEX_NAME}.txt".format(**common,
                        IN_SUB_DIR = sub_dir,
                        OUT_PREFIX = out_prefix
                    )
                )
            ]
            # Copy the pool file
            if use_pool_bundle:
                output_pkg = " {OUT_DIR}/{OUT_PREFIX}pool.res".format(**common, OUT_PREFIX = out_prefix)
                requests += [
                    ExecutionRequest(
                        dep_files = output_files + [index_res_file],
                        input_files = output_files + [index_res_file],
                        output_files = [output_pkg],
                        tool = "icupkg",
                        args = "-t{ICUDATA_CHAR} {IN_DIR}/{IN_SUB_DIR}/pool.res {OUT_DIR}/{OUT_PREFIX}pool.res".format(**common,
                            IN_SUB_DIR = sub_dir,
                            OUT_PREFIX = out_prefix
                        )
                    )
                ]


    for request in requests:
        command_lines = get_command_lines(request, common)
        for command_line in command_lines:
            print(command_line)

main()
